// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockTokenVerifier creates a new instance of mockTokenVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTokenVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTokenVerifier {
	mock := &mockTokenVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockTokenVerifier is an autogenerated mock type for the TokenVerifier type
type mockTokenVerifier struct {
	mock.Mock
}

type mockTokenVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTokenVerifier) EXPECT() *mockTokenVerifier_Expecter {
	return &mockTokenVerifier_Expecter{mock: &_m.Mock}
}

// VerifyAccessToken provides a mock function for the type mockTokenVerifier
func (_mock *mockTokenVerifier) VerifyAccessToken(token string) (map[string]any, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAccessToken")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (map[string]any, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]any); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockTokenVerifier_VerifyAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAccessToken'
type mockTokenVerifier_VerifyAccessToken_Call struct {
	*mock.Call
}

// VerifyAccessToken is a helper method to define mock.On call
//   - token string
func (_e *mockTokenVerifier_Expecter) VerifyAccessToken(token any) *mockTokenVerifier_VerifyAccessToken_Call {
	return &mockTokenVerifier_VerifyAccessToken_Call{Call: _e.mock.On("VerifyAccessToken", token)}
}

func (_c *mockTokenVerifier_VerifyAccessToken_Call) Run(run func(token string)) *mockTokenVerifier_VerifyAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockTokenVerifier_VerifyAccessToken_Call) Return(stringToAnyMoqParam map[string]any, err error) *mockTokenVerifier_VerifyAccessToken_Call {
	_c.Call.Return(stringToAnyMoqParam, err)
	return _c
}

func (_c *mockTokenVerifier_VerifyAccessToken_Call) RunAndReturn(run func(token string) (map[string]any, error)) *mockTokenVerifier_VerifyAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
