// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package idp

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/willie68/arcivio/internal/domain/identity"
)

// newMockIdentityService creates a new instance of mockIdentityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIdentityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIdentityService {
	mock := &mockIdentityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockIdentityService is an autogenerated mock type for the identityService type
type mockIdentityService struct {
	mock.Mock
}

type mockIdentityService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIdentityService) EXPECT() *mockIdentityService_Expecter {
	return &mockIdentityService_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type mockIdentityService
func (_mock *mockIdentityService) Authenticate(ctx context.Context, username string, password string) (*identity.User, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *identity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*identity.User, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *identity.User); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockIdentityService_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type mockIdentityService_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *mockIdentityService_Expecter) Authenticate(ctx any, username any, password any) *mockIdentityService_Authenticate_Call {
	return &mockIdentityService_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, username, password)}
}

func (_c *mockIdentityService_Authenticate_Call) Run(run func(ctx context.Context, username string, password string)) *mockIdentityService_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockIdentityService_Authenticate_Call) Return(user *identity.User, err error) *mockIdentityService_Authenticate_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockIdentityService_Authenticate_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (*identity.User, error)) *mockIdentityService_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// ChangePassword provides a mock function for the type mockIdentityService
func (_mock *mockIdentityService) ChangePassword(ctx context.Context, userID string, oldPassword string, newPassword string) (*identity.User, error) {
	ret := _mock.Called(ctx, userID, oldPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 *identity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*identity.User, error)); ok {
		return returnFunc(ctx, userID, oldPassword, newPassword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *identity.User); ok {
		r0 = returnFunc(ctx, userID, oldPassword, newPassword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, oldPassword, newPassword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockIdentityService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type mockIdentityService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - oldPassword string
//   - newPassword string
func (_e *mockIdentityService_Expecter) ChangePassword(ctx any, userID any, oldPassword any, newPassword any) *mockIdentityService_ChangePassword_Call {
	return &mockIdentityService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, oldPassword, newPassword)}
}

func (_c *mockIdentityService_ChangePassword_Call) Run(run func(ctx context.Context, userID string, oldPassword string, newPassword string)) *mockIdentityService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockIdentityService_ChangePassword_Call) Return(user *identity.User, err error) *mockIdentityService_ChangePassword_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockIdentityService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, userID string, oldPassword string, newPassword string) (*identity.User, error)) *mockIdentityService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type mockIdentityService
func (_mock *mockIdentityService) CreateUser(ctx context.Context, in identity.NewUser) (*identity.User, string, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *identity.User
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, identity.NewUser) (*identity.User, string, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, identity.NewUser) *identity.User); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, identity.NewUser) string); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, identity.NewUser) error); ok {
		r2 = returnFunc(ctx, in)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockIdentityService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type mockIdentityService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in identity.NewUser
func (_e *mockIdentityService_Expecter) CreateUser(ctx any, in any) *mockIdentityService_CreateUser_Call {
	return &mockIdentityService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, in)}
}

func (_c *mockIdentityService_CreateUser_Call) Run(run func(ctx context.Context, in identity.NewUser)) *mockIdentityService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 identity.NewUser
		if args[1] != nil {
			arg1 = args[1].(identity.NewUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockIdentityService_CreateUser_Call) Return(user *identity.User, s string, err error) *mockIdentityService_CreateUser_Call {
	_c.Call.Return(user, s, err)
	return _c
}

func (_c *mockIdentityService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, in identity.NewUser) (*identity.User, string, error)) *mockIdentityService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type mockIdentityService
func (_mock *mockIdentityService) DeleteUser(ctx context.Context, actorID string, userID string) error {
	ret := _mock.Called(ctx, actorID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, actorID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockIdentityService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type mockIdentityService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - userID string
func (_e *mockIdentityService_Expecter) DeleteUser(ctx any, actorID any, userID any) *mockIdentityService_DeleteUser_Call {
	return &mockIdentityService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, actorID, userID)}
}

func (_c *mockIdentityService_DeleteUser_Call) Run(run func(ctx context.Context, actorID string, userID string)) *mockIdentityService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockIdentityService_DeleteUser_Call) Return(err error) *mockIdentityService_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockIdentityService_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, actorID string, userID string) error) *mockIdentityService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type mockIdentityService
func (_mock *mockIdentityService) GetByID(ctx context.Context, id string) (*identity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *identity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*identity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *identity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockIdentityService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type mockIdentityService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockIdentityService_Expecter) GetByID(ctx any, id any) *mockIdentityService_GetByID_Call {
	return &mockIdentityService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *mockIdentityService_GetByID_Call) Run(run func(ctx context.Context, id string)) *mockIdentityService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockIdentityService_GetByID_Call) Return(user *identity.User, err error) *mockIdentityService_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockIdentityService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*identity.User, error)) *mockIdentityService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type mockIdentityService
func (_mock *mockIdentityService) ListUsers(ctx context.Context, offset int, limit int, sort string, desc bool, prefix string) ([]identity.User, int, error) {
	ret := _mock.Called(ctx, offset, limit, sort, desc, prefix)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []identity.User
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string, bool, string) ([]identity.User, int, error)); ok {
		return returnFunc(ctx, offset, limit, sort, desc, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string, bool, string) []identity.User); ok {
		r0 = returnFunc(ctx, offset, limit, sort, desc, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]identity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, string, bool, string) int); ok {
		r1 = returnFunc(ctx, offset, limit, sort, desc, prefix)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int, string, bool, string) error); ok {
		r2 = returnFunc(ctx, offset, limit, sort, desc, prefix)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockIdentityService_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type mockIdentityService_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
//   - sort string
//   - desc bool
//   - prefix string
func (_e *mockIdentityService_Expecter) ListUsers(ctx any, offset any, limit any, sort any, desc any, prefix any) *mockIdentityService_ListUsers_Call {
	return &mockIdentityService_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, offset, limit, sort, desc, prefix)}
}

func (_c *mockIdentityService_ListUsers_Call) Run(run func(ctx context.Context, offset int, limit int, sort string, desc bool, prefix string)) *mockIdentityService_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockIdentityService_ListUsers_Call) Return(users []identity.User, n int, err error) *mockIdentityService_ListUsers_Call {
	_c.Call.Return(users, n, err)
	return _c
}

func (_c *mockIdentityService_ListUsers_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int, sort string, desc bool, prefix string) ([]identity.User, int, error)) *mockIdentityService_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function for the type mockIdentityService
func (_mock *mockIdentityService) ResetPassword(ctx context.Context, userID string) (*identity.User, string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 *identity.User
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*identity.User, string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *identity.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockIdentityService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type mockIdentityService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockIdentityService_Expecter) ResetPassword(ctx any, userID any) *mockIdentityService_ResetPassword_Call {
	return &mockIdentityService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, userID)}
}

func (_c *mockIdentityService_ResetPassword_Call) Run(run func(ctx context.Context, userID string)) *mockIdentityService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockIdentityService_ResetPassword_Call) Return(user *identity.User, s string, err error) *mockIdentityService_ResetPassword_Call {
	_c.Call.Return(user, s, err)
	return _c
}

func (_c *mockIdentityService_ResetPassword_Call) RunAndReturn(run func(ctx context.Context, userID string) (*identity.User, string, error)) *mockIdentityService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type mockIdentityService
func (_mock *mockIdentityService) UpdateProfile(ctx context.Context, userID string, in identity.ProfilePatch) (*identity.User, error) {
	ret := _mock.Called(ctx, userID, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *identity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, identity.ProfilePatch) (*identity.User, error)); ok {
		return returnFunc(ctx, userID, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, identity.ProfilePatch) *identity.User); ok {
		r0 = returnFunc(ctx, userID, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, identity.ProfilePatch) error); ok {
		r1 = returnFunc(ctx, userID, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockIdentityService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type mockIdentityService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - in identity.ProfilePatch
func (_e *mockIdentityService_Expecter) UpdateProfile(ctx any, userID any, in any) *mockIdentityService_UpdateProfile_Call {
	return &mockIdentityService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, in)}
}

func (_c *mockIdentityService_UpdateProfile_Call) Run(run func(ctx context.Context, userID string, in identity.ProfilePatch)) *mockIdentityService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 identity.ProfilePatch
		if args[2] != nil {
			arg2 = args[2].(identity.ProfilePatch)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockIdentityService_UpdateProfile_Call) Return(user *identity.User, err error) *mockIdentityService_UpdateProfile_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockIdentityService_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, userID string, in identity.ProfilePatch) (*identity.User, error)) *mockIdentityService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type mockIdentityService
func (_mock *mockIdentityService) UpdateUser(ctx context.Context, userID string, in identity.UserPatch) (*identity.User, error) {
	ret := _mock.Called(ctx, userID, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *identity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, identity.UserPatch) (*identity.User, error)); ok {
		return returnFunc(ctx, userID, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, identity.UserPatch) *identity.User); ok {
		r0 = returnFunc(ctx, userID, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, identity.UserPatch) error); ok {
		r1 = returnFunc(ctx, userID, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockIdentityService_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type mockIdentityService_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - in identity.UserPatch
func (_e *mockIdentityService_Expecter) UpdateUser(ctx any, userID any, in any) *mockIdentityService_UpdateUser_Call {
	return &mockIdentityService_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, userID, in)}
}

func (_c *mockIdentityService_UpdateUser_Call) Run(run func(ctx context.Context, userID string, in identity.UserPatch)) *mockIdentityService_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 identity.UserPatch
		if args[2] != nil {
			arg2 = args[2].(identity.UserPatch)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockIdentityService_UpdateUser_Call) Return(user *identity.User, err error) *mockIdentityService_UpdateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockIdentityService_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, userID string, in identity.UserPatch) (*identity.User, error)) *mockIdentityService_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
