// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package shttp

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockSrvConfig creates a new instance of mockSrvConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSrvConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSrvConfig {
	mock := &mockSrvConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockSrvConfig is an autogenerated mock type for the srvConfig type
type mockSrvConfig struct {
	mock.Mock
}

type mockSrvConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSrvConfig) EXPECT() *mockSrvConfig_Expecter {
	return &mockSrvConfig_Expecter{mock: &_m.Mock}
}

// GetHttpConfig provides a mock function for the type mockSrvConfig
func (_mock *mockSrvConfig) GetHttpConfig() Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHttpConfig")
	}

	var r0 Config
	if returnFunc, ok := ret.Get(0).(func() Config); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(Config)
	}
	return r0
}

// mockSrvConfig_GetHttpConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHttpConfig'
type mockSrvConfig_GetHttpConfig_Call struct {
	*mock.Call
}

// GetHttpConfig is a helper method to define mock.On call
func (_e *mockSrvConfig_Expecter) GetHttpConfig() *mockSrvConfig_GetHttpConfig_Call {
	return &mockSrvConfig_GetHttpConfig_Call{Call: _e.mock.On("GetHttpConfig")}
}

func (_c *mockSrvConfig_GetHttpConfig_Call) Run(run func()) *mockSrvConfig_GetHttpConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockSrvConfig_GetHttpConfig_Call) Return(config Config) *mockSrvConfig_GetHttpConfig_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *mockSrvConfig_GetHttpConfig_Call) RunAndReturn(run func() Config) *mockSrvConfig_GetHttpConfig_Call {
	_c.Call.Return(run)
	return _c
}
