// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"github.com/go-chi/chi/v5"
	mock "github.com/stretchr/testify/mock"
)

// newMockHandler creates a new instance of mockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockHandler {
	mock := &mockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockHandler is an autogenerated mock type for the Handler type
type mockHandler struct {
	mock.Mock
}

type mockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHandler) EXPECT() *mockHandler_Expecter {
	return &mockHandler_Expecter{mock: &_m.Mock}
}

// Routes provides a mock function for the type mockHandler
func (_mock *mockHandler) Routes() (string, *chi.Mux) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Routes")
	}

	var r0 string
	var r1 *chi.Mux
	if returnFunc, ok := ret.Get(0).(func() (string, *chi.Mux)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() *chi.Mux); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*chi.Mux)
		}
	}
	return r0, r1
}

// mockHandler_Routes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Routes'
type mockHandler_Routes_Call struct {
	*mock.Call
}

// Routes is a helper method to define mock.On call
func (_e *mockHandler_Expecter) Routes() *mockHandler_Routes_Call {
	return &mockHandler_Routes_Call{Call: _e.mock.On("Routes")}
}

func (_c *mockHandler_Routes_Call) Run(run func()) *mockHandler_Routes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockHandler_Routes_Call) Return(s string, mux *chi.Mux) *mockHandler_Routes_Call {
	_c.Call.Return(s, mux)
	return _c
}

func (_c *mockHandler_Routes_Call) RunAndReturn(run func() (string, *chi.Mux)) *mockHandler_Routes_Call {
	_c.Call.Return(run)
	return _c
}
