// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv1

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/willie68/arcivio/internal/domain/identity"
)

// newMockIdentityService creates a new instance of mockIdentityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIdentityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIdentityService {
	mock := &mockIdentityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockIdentityService is an autogenerated mock type for the identityService type
type mockIdentityService struct {
	mock.Mock
}

type mockIdentityService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIdentityService) EXPECT() *mockIdentityService_Expecter {
	return &mockIdentityService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type mockIdentityService
func (_mock *mockIdentityService) ChangePassword(ctx context.Context, userID string, oldPassword string, newPassword string) (*identity.User, error) {
	ret := _mock.Called(ctx, userID, oldPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 *identity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*identity.User, error)); ok {
		return returnFunc(ctx, userID, oldPassword, newPassword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *identity.User); ok {
		r0 = returnFunc(ctx, userID, oldPassword, newPassword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, oldPassword, newPassword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockIdentityService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type mockIdentityService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - oldPassword string
//   - newPassword string
func (_e *mockIdentityService_Expecter) ChangePassword(ctx any, userID any, oldPassword any, newPassword any) *mockIdentityService_ChangePassword_Call {
	return &mockIdentityService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, oldPassword, newPassword)}
}

func (_c *mockIdentityService_ChangePassword_Call) Run(run func(ctx context.Context, userID string, oldPassword string, newPassword string)) *mockIdentityService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockIdentityService_ChangePassword_Call) Return(user *identity.User, err error) *mockIdentityService_ChangePassword_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockIdentityService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, userID string, oldPassword string, newPassword string) (*identity.User, error)) *mockIdentityService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type mockIdentityService
func (_mock *mockIdentityService) GetByID(ctx context.Context, id string) (*identity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *identity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*identity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *identity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockIdentityService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type mockIdentityService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockIdentityService_Expecter) GetByID(ctx any, id any) *mockIdentityService_GetByID_Call {
	return &mockIdentityService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *mockIdentityService_GetByID_Call) Run(run func(ctx context.Context, id string)) *mockIdentityService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockIdentityService_GetByID_Call) Return(user *identity.User, err error) *mockIdentityService_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockIdentityService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*identity.User, error)) *mockIdentityService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type mockIdentityService
func (_mock *mockIdentityService) UpdateProfile(ctx context.Context, userID string, in identity.ProfilePatch) (*identity.User, error) {
	ret := _mock.Called(ctx, userID, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *identity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, identity.ProfilePatch) (*identity.User, error)); ok {
		return returnFunc(ctx, userID, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, identity.ProfilePatch) *identity.User); ok {
		r0 = returnFunc(ctx, userID, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, identity.ProfilePatch) error); ok {
		r1 = returnFunc(ctx, userID, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockIdentityService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type mockIdentityService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - in identity.ProfilePatch
func (_e *mockIdentityService_Expecter) UpdateProfile(ctx any, userID any, in any) *mockIdentityService_UpdateProfile_Call {
	return &mockIdentityService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, in)}
}

func (_c *mockIdentityService_UpdateProfile_Call) Run(run func(ctx context.Context, userID string, in identity.ProfilePatch)) *mockIdentityService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 identity.ProfilePatch
		if args[2] != nil {
			arg2 = args[2].(identity.ProfilePatch)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockIdentityService_UpdateProfile_Call) Return(user *identity.User, err error) *mockIdentityService_UpdateProfile_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockIdentityService_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, userID string, in identity.ProfilePatch) (*identity.User, error)) *mockIdentityService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}
