// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package document

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockStore creates a new instance of mockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStore {
	mock := &mockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockStore is an autogenerated mock type for the Store type
type mockStore struct {
	mock.Mock
}

type mockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStore) EXPECT() *mockStore_Expecter {
	return &mockStore_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type mockStore
func (_mock *mockStore) Ping() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockStore_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type mockStore_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *mockStore_Expecter) Ping() *mockStore_Ping_Call {
	return &mockStore_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *mockStore_Ping_Call) Run(run func()) *mockStore_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockStore_Ping_Call) Return(err error) *mockStore_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockStore_Ping_Call) RunAndReturn(run func() error) *mockStore_Ping_Call {
	_c.Call.Return(run)
	return _c
}
