// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package health

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// newMockCheck creates a new instance of mockCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCheck {
	mock := &mockCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockCheck is an autogenerated mock type for the Check type
type mockCheck struct {
	mock.Mock
}

type mockCheck_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCheck) EXPECT() *mockCheck_Expecter {
	return &mockCheck_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type mockCheck
func (_mock *mockCheck) Check() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockCheck_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type mockCheck_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
func (_e *mockCheck_Expecter) Check() *mockCheck_Check_Call {
	return &mockCheck_Check_Call{Call: _e.mock.On("Check")}
}

func (_c *mockCheck_Check_Call) Run(run func()) *mockCheck_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCheck_Check_Call) Return(b bool, err error) *mockCheck_Check_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockCheck_Check_Call) RunAndReturn(run func() (bool, error)) *mockCheck_Check_Call {
	_c.Call.Return(run)
	return _c
}

// CheckName provides a mock function for the type mockCheck
func (_mock *mockCheck) CheckName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockCheck_CheckName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckName'
type mockCheck_CheckName_Call struct {
	*mock.Call
}

// CheckName is a helper method to define mock.On call
func (_e *mockCheck_Expecter) CheckName() *mockCheck_CheckName_Call {
	return &mockCheck_CheckName_Call{Call: _e.mock.On("CheckName")}
}

func (_c *mockCheck_CheckName_Call) Run(run func()) *mockCheck_CheckName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCheck_CheckName_Call) Return(s string) *mockCheck_CheckName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockCheck_CheckName_Call) RunAndReturn(run func() string) *mockCheck_CheckName_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRegisterer creates a new instance of mockRegisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRegisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRegisterer {
	mock := &mockRegisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockRegisterer is an autogenerated mock type for the Registerer type
type mockRegisterer struct {
	mock.Mock
}

type mockRegisterer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRegisterer) EXPECT() *mockRegisterer_Expecter {
	return &mockRegisterer_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type mockRegisterer
func (_mock *mockRegisterer) Register(check Check) {
	_mock.Called(check)
	return
}

// mockRegisterer_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type mockRegisterer_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - check Check
func (_e *mockRegisterer_Expecter) Register(check any) *mockRegisterer_Register_Call {
	return &mockRegisterer_Register_Call{Call: _e.mock.On("Register", check)}
}

func (_c *mockRegisterer_Register_Call) Run(run func(check Check)) *mockRegisterer_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Check
		if args[0] != nil {
			arg0 = args[0].(Check)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockRegisterer_Register_Call) Return() *mockRegisterer_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockRegisterer_Register_Call) RunAndReturn(run func(check Check)) *mockRegisterer_Register_Call {
	_c.Run(run)
	return _c
}

// newMockUnregisterer creates a new instance of mockUnregisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUnregisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUnregisterer {
	mock := &mockUnregisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockUnregisterer is an autogenerated mock type for the Unregisterer type
type mockUnregisterer struct {
	mock.Mock
}

type mockUnregisterer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUnregisterer) EXPECT() *mockUnregisterer_Expecter {
	return &mockUnregisterer_Expecter{mock: &_m.Mock}
}

// Unregister provides a mock function for the type mockUnregisterer
func (_mock *mockUnregisterer) Unregister(checkname string) bool {
	ret := _mock.Called(checkname)

	if len(ret) == 0 {
		panic("no return value specified for Unregister")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(checkname)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockUnregisterer_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type mockUnregisterer_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//   - checkname string
func (_e *mockUnregisterer_Expecter) Unregister(checkname any) *mockUnregisterer_Unregister_Call {
	return &mockUnregisterer_Unregister_Call{Call: _e.mock.On("Unregister", checkname)}
}

func (_c *mockUnregisterer_Unregister_Call) Run(run func(checkname string)) *mockUnregisterer_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockUnregisterer_Unregister_Call) Return(b bool) *mockUnregisterer_Unregister_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockUnregisterer_Unregister_Call) RunAndReturn(run func(checkname string) bool) *mockUnregisterer_Unregister_Call {
	_c.Call.Return(run)
	return _c
}

// newMockHealthy creates a new instance of mockHealthy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockHealthy(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockHealthy {
	mock := &mockHealthy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockHealthy is an autogenerated mock type for the Healthy type
type mockHealthy struct {
	mock.Mock
}

type mockHealthy_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHealthy) EXPECT() *mockHealthy_Expecter {
	return &mockHealthy_Expecter{mock: &_m.Mock}
}

// CheckHealthCheckTimer provides a mock function for the type mockHealthy
func (_mock *mockHealthy) CheckHealthCheckTimer() {
	_mock.Called()
	return
}

// mockHealthy_CheckHealthCheckTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHealthCheckTimer'
type mockHealthy_CheckHealthCheckTimer_Call struct {
	*mock.Call
}

// CheckHealthCheckTimer is a helper method to define mock.On call
func (_e *mockHealthy_Expecter) CheckHealthCheckTimer() *mockHealthy_CheckHealthCheckTimer_Call {
	return &mockHealthy_CheckHealthCheckTimer_Call{Call: _e.mock.On("CheckHealthCheckTimer")}
}

func (_c *mockHealthy_CheckHealthCheckTimer_Call) Run(run func()) *mockHealthy_CheckHealthCheckTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockHealthy_CheckHealthCheckTimer_Call) Return() *mockHealthy_CheckHealthCheckTimer_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockHealthy_CheckHealthCheckTimer_Call) RunAndReturn(run func()) *mockHealthy_CheckHealthCheckTimer_Call {
	_c.Run(run)
	return _c
}

// Healthyz provides a mock function for the type mockHealthy
func (_mock *mockHealthy) Healthyz() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Healthyz")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockHealthy_Healthyz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Healthyz'
type mockHealthy_Healthyz_Call struct {
	*mock.Call
}

// Healthyz is a helper method to define mock.On call
func (_e *mockHealthy_Expecter) Healthyz() *mockHealthy_Healthyz_Call {
	return &mockHealthy_Healthyz_Call{Call: _e.mock.On("Healthyz")}
}

func (_c *mockHealthy_Healthyz_Call) Run(run func()) *mockHealthy_Healthyz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockHealthy_Healthyz_Call) Return(b bool) *mockHealthy_Healthyz_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockHealthy_Healthyz_Call) RunAndReturn(run func() bool) *mockHealthy_Healthyz_Call {
	_c.Call.Return(run)
	return _c
}

// LastChecked provides a mock function for the type mockHealthy
func (_mock *mockHealthy) LastChecked() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastChecked")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// mockHealthy_LastChecked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastChecked'
type mockHealthy_LastChecked_Call struct {
	*mock.Call
}

// LastChecked is a helper method to define mock.On call
func (_e *mockHealthy_Expecter) LastChecked() *mockHealthy_LastChecked_Call {
	return &mockHealthy_LastChecked_Call{Call: _e.mock.On("LastChecked")}
}

func (_c *mockHealthy_LastChecked_Call) Run(run func()) *mockHealthy_LastChecked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockHealthy_LastChecked_Call) Return(time1 time.Time) *mockHealthy_LastChecked_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *mockHealthy_LastChecked_Call) RunAndReturn(run func() time.Time) *mockHealthy_LastChecked_Call {
	_c.Call.Return(run)
	return _c
}

// Message provides a mock function for the type mockHealthy
func (_mock *mockHealthy) Message() Message {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 Message
	if returnFunc, ok := ret.Get(0).(func() Message); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(Message)
	}
	return r0
}

// mockHealthy_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type mockHealthy_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *mockHealthy_Expecter) Message() *mockHealthy_Message_Call {
	return &mockHealthy_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *mockHealthy_Message_Call) Run(run func()) *mockHealthy_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockHealthy_Message_Call) Return(message Message) *mockHealthy_Message_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *mockHealthy_Message_Call) RunAndReturn(run func() Message) *mockHealthy_Message_Call {
	_c.Call.Return(run)
	return _c
}

// Readyz provides a mock function for the type mockHealthy
func (_mock *mockHealthy) Readyz() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Readyz")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockHealthy_Readyz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Readyz'
type mockHealthy_Readyz_Call struct {
	*mock.Call
}

// Readyz is a helper method to define mock.On call
func (_e *mockHealthy_Expecter) Readyz() *mockHealthy_Readyz_Call {
	return &mockHealthy_Readyz_Call{Call: _e.mock.On("Readyz")}
}

func (_c *mockHealthy_Readyz_Call) Run(run func()) *mockHealthy_Readyz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockHealthy_Readyz_Call) Return(b bool) *mockHealthy_Readyz_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockHealthy_Readyz_Call) RunAndReturn(run func() bool) *mockHealthy_Readyz_Call {
	_c.Call.Return(run)
	return _c
}

// newMockServiceName creates a new instance of mockServiceName. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockServiceName(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockServiceName {
	mock := &mockServiceName{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockServiceName is an autogenerated mock type for the ServiceName type
type mockServiceName struct {
	mock.Mock
}

type mockServiceName_Expecter struct {
	mock *mock.Mock
}

func (_m *mockServiceName) EXPECT() *mockServiceName_Expecter {
	return &mockServiceName_Expecter{mock: &_m.Mock}
}

// ServiceName provides a mock function for the type mockServiceName
func (_mock *mockServiceName) ServiceName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockServiceName_ServiceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceName'
type mockServiceName_ServiceName_Call struct {
	*mock.Call
}

// ServiceName is a helper method to define mock.On call
func (_e *mockServiceName_Expecter) ServiceName() *mockServiceName_ServiceName_Call {
	return &mockServiceName_ServiceName_Call{Call: _e.mock.On("ServiceName")}
}

func (_c *mockServiceName_ServiceName_Call) Run(run func()) *mockServiceName_ServiceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockServiceName_ServiceName_Call) Return(s string) *mockServiceName_ServiceName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockServiceName_ServiceName_Call) RunAndReturn(run func() string) *mockServiceName_ServiceName_Call {
	_c.Call.Return(run)
	return _c
}
