// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package identity

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// newMockUserStore creates a new instance of mockUserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUserStore {
	mock := &mockUserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockUserStore is an autogenerated mock type for the UserStore type
type mockUserStore struct {
	mock.Mock
}

type mockUserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUserStore) EXPECT() *mockUserStore_Expecter {
	return &mockUserStore_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type mockUserStore
func (_mock *mockUserStore) Count(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockUserStore_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type mockUserStore_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockUserStore_Expecter) Count(ctx any) *mockUserStore_Count_Call {
	return &mockUserStore_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *mockUserStore_Count_Call) Run(run func(ctx context.Context)) *mockUserStore_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockUserStore_Count_Call) Return(n int, err error) *mockUserStore_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockUserStore_Count_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *mockUserStore_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountWithRole provides a mock function for the type mockUserStore
func (_mock *mockUserStore) CountWithRole(ctx context.Context, role string) (int, error) {
	ret := _mock.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for CountWithRole")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, role)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockUserStore_CountWithRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountWithRole'
type mockUserStore_CountWithRole_Call struct {
	*mock.Call
}

// CountWithRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
func (_e *mockUserStore_Expecter) CountWithRole(ctx any, role any) *mockUserStore_CountWithRole_Call {
	return &mockUserStore_CountWithRole_Call{Call: _e.mock.On("CountWithRole", ctx, role)}
}

func (_c *mockUserStore_CountWithRole_Call) Run(run func(ctx context.Context, role string)) *mockUserStore_CountWithRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockUserStore_CountWithRole_Call) Return(n int, err error) *mockUserStore_CountWithRole_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockUserStore_CountWithRole_Call) RunAndReturn(run func(ctx context.Context, role string) (int, error)) *mockUserStore_CountWithRole_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type mockUserStore
func (_mock *mockUserStore) Create(ctx context.Context, user User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockUserStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockUserStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user User
func (_e *mockUserStore_Expecter) Create(ctx any, user any) *mockUserStore_Create_Call {
	return &mockUserStore_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *mockUserStore_Create_Call) Run(run func(ctx context.Context, user User)) *mockUserStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 User
		if args[1] != nil {
			arg1 = args[1].(User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockUserStore_Create_Call) Return(err error) *mockUserStore_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockUserStore_Create_Call) RunAndReturn(run func(ctx context.Context, user User) error) *mockUserStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type mockUserStore
func (_mock *mockUserStore) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockUserStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockUserStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockUserStore_Expecter) Delete(ctx any, id any) *mockUserStore_Delete_Call {
	return &mockUserStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *mockUserStore_Delete_Call) Run(run func(ctx context.Context, id string)) *mockUserStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockUserStore_Delete_Call) Return(err error) *mockUserStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockUserStore_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *mockUserStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type mockUserStore
func (_mock *mockUserStore) GetByID(ctx context.Context, id string) (*User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockUserStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type mockUserStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockUserStore_Expecter) GetByID(ctx any, id any) *mockUserStore_GetByID_Call {
	return &mockUserStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *mockUserStore_GetByID_Call) Run(run func(ctx context.Context, id string)) *mockUserStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockUserStore_GetByID_Call) Return(user *User, err error) *mockUserStore_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockUserStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*User, error)) *mockUserStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type mockUserStore
func (_mock *mockUserStore) GetByUsername(ctx context.Context, username string) (*User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockUserStore_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type mockUserStore_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *mockUserStore_Expecter) GetByUsername(ctx any, username any) *mockUserStore_GetByUsername_Call {
	return &mockUserStore_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *mockUserStore_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *mockUserStore_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockUserStore_GetByUsername_Call) Return(user *User, err error) *mockUserStore_GetByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockUserStore_GetByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*User, error)) *mockUserStore_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type mockUserStore
func (_mock *mockUserStore) List(ctx context.Context, offset int, limit int, sort string, desc bool, prefix string) ([]User, int, error) {
	ret := _mock.Called(ctx, offset, limit, sort, desc, prefix)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []User
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string, bool, string) ([]User, int, error)); ok {
		return returnFunc(ctx, offset, limit, sort, desc, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string, bool, string) []User); ok {
		r0 = returnFunc(ctx, offset, limit, sort, desc, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, string, bool, string) int); ok {
		r1 = returnFunc(ctx, offset, limit, sort, desc, prefix)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int, string, bool, string) error); ok {
		r2 = returnFunc(ctx, offset, limit, sort, desc, prefix)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockUserStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockUserStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
//   - sort string
//   - desc bool
//   - prefix string
func (_e *mockUserStore_Expecter) List(ctx any, offset any, limit any, sort any, desc any, prefix any) *mockUserStore_List_Call {
	return &mockUserStore_List_Call{Call: _e.mock.On("List", ctx, offset, limit, sort, desc, prefix)}
}

func (_c *mockUserStore_List_Call) Run(run func(ctx context.Context, offset int, limit int, sort string, desc bool, prefix string)) *mockUserStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockUserStore_List_Call) Return(users []User, n int, err error) *mockUserStore_List_Call {
	_c.Call.Return(users, n, err)
	return _c
}

func (_c *mockUserStore_List_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int, sort string, desc bool, prefix string) ([]User, int, error)) *mockUserStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// RecordLastLogin provides a mock function for the type mockUserStore
func (_mock *mockUserStore) RecordLastLogin(ctx context.Context, userID string, at time.Time) error {
	ret := _mock.Called(ctx, userID, at)

	if len(ret) == 0 {
		panic("no return value specified for RecordLastLogin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockUserStore_RecordLastLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordLastLogin'
type mockUserStore_RecordLastLogin_Call struct {
	*mock.Call
}

// RecordLastLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - at time.Time
func (_e *mockUserStore_Expecter) RecordLastLogin(ctx any, userID any, at any) *mockUserStore_RecordLastLogin_Call {
	return &mockUserStore_RecordLastLogin_Call{Call: _e.mock.On("RecordLastLogin", ctx, userID, at)}
}

func (_c *mockUserStore_RecordLastLogin_Call) Run(run func(ctx context.Context, userID string, at time.Time)) *mockUserStore_RecordLastLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockUserStore_RecordLastLogin_Call) Return(err error) *mockUserStore_RecordLastLogin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockUserStore_RecordLastLogin_Call) RunAndReturn(run func(ctx context.Context, userID string, at time.Time) error) *mockUserStore_RecordLastLogin_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type mockUserStore
func (_mock *mockUserStore) Update(ctx context.Context, user User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockUserStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockUserStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user User
func (_e *mockUserStore_Expecter) Update(ctx any, user any) *mockUserStore_Update_Call {
	return &mockUserStore_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *mockUserStore_Update_Call) Run(run func(ctx context.Context, user User)) *mockUserStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 User
		if args[1] != nil {
			arg1 = args[1].(User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockUserStore_Update_Call) Return(err error) *mockUserStore_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockUserStore_Update_Call) RunAndReturn(run func(ctx context.Context, user User) error) *mockUserStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPasswordHasher creates a new instance of mockPasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPasswordHasher {
	mock := &mockPasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockPasswordHasher is an autogenerated mock type for the PasswordHasher type
type mockPasswordHasher struct {
	mock.Mock
}

type mockPasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPasswordHasher) EXPECT() *mockPasswordHasher_Expecter {
	return &mockPasswordHasher_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type mockPasswordHasher
func (_mock *mockPasswordHasher) Hash(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPasswordHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type mockPasswordHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *mockPasswordHasher_Expecter) Hash(password any) *mockPasswordHasher_Hash_Call {
	return &mockPasswordHasher_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *mockPasswordHasher_Hash_Call) Run(run func(password string)) *mockPasswordHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockPasswordHasher_Hash_Call) Return(s string, err error) *mockPasswordHasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockPasswordHasher_Hash_Call) RunAndReturn(run func(password string) (string, error)) *mockPasswordHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type mockPasswordHasher
func (_mock *mockPasswordHasher) Verify(encodedHash string, password string) error {
	ret := _mock.Called(encodedHash, password)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(encodedHash, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockPasswordHasher_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type mockPasswordHasher_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - encodedHash string
//   - password string
func (_e *mockPasswordHasher_Expecter) Verify(encodedHash any, password any) *mockPasswordHasher_Verify_Call {
	return &mockPasswordHasher_Verify_Call{Call: _e.mock.On("Verify", encodedHash, password)}
}

func (_c *mockPasswordHasher_Verify_Call) Run(run func(encodedHash string, password string)) *mockPasswordHasher_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockPasswordHasher_Verify_Call) Return(err error) *mockPasswordHasher_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockPasswordHasher_Verify_Call) RunAndReturn(run func(encodedHash string, password string) error) *mockPasswordHasher_Verify_Call {
	_c.Call.Return(run)
	return _c
}
