// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package main

import (
	"github.com/go-chi/chi/v5"
	mock "github.com/stretchr/testify/mock"
)

// newMockSHttp creates a new instance of mockSHttp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSHttp(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSHttp {
	mock := &mockSHttp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockSHttp is an autogenerated mock type for the SHttp type
type mockSHttp struct {
	mock.Mock
}

type mockSHttp_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSHttp) EXPECT() *mockSHttp_Expecter {
	return &mockSHttp_Expecter{mock: &_m.Mock}
}

// ShutdownServers provides a mock function for the type mockSHttp
func (_mock *mockSHttp) ShutdownServers() {
	_mock.Called()
	return
}

// mockSHttp_ShutdownServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShutdownServers'
type mockSHttp_ShutdownServers_Call struct {
	*mock.Call
}

// ShutdownServers is a helper method to define mock.On call
func (_e *mockSHttp_Expecter) ShutdownServers() *mockSHttp_ShutdownServers_Call {
	return &mockSHttp_ShutdownServers_Call{Call: _e.mock.On("ShutdownServers")}
}

func (_c *mockSHttp_ShutdownServers_Call) Run(run func()) *mockSHttp_ShutdownServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockSHttp_ShutdownServers_Call) Return() *mockSHttp_ShutdownServers_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockSHttp_ShutdownServers_Call) RunAndReturn(run func()) *mockSHttp_ShutdownServers_Call {
	_c.Run(run)
	return _c
}

// StartServers provides a mock function for the type mockSHttp
func (_mock *mockSHttp) StartServers(router *chi.Mux, healthRouter *chi.Mux) {
	_mock.Called(router, healthRouter)
	return
}

// mockSHttp_StartServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartServers'
type mockSHttp_StartServers_Call struct {
	*mock.Call
}

// StartServers is a helper method to define mock.On call
//   - router *chi.Mux
//   - healthRouter *chi.Mux
func (_e *mockSHttp_Expecter) StartServers(router any, healthRouter any) *mockSHttp_StartServers_Call {
	return &mockSHttp_StartServers_Call{Call: _e.mock.On("StartServers", router, healthRouter)}
}

func (_c *mockSHttp_StartServers_Call) Run(run func(router *chi.Mux, healthRouter *chi.Mux)) *mockSHttp_StartServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *chi.Mux
		if args[0] != nil {
			arg0 = args[0].(*chi.Mux)
		}
		var arg1 *chi.Mux
		if args[1] != nil {
			arg1 = args[1].(*chi.Mux)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockSHttp_StartServers_Call) Return() *mockSHttp_StartServers_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockSHttp_StartServers_Call) RunAndReturn(run func(router *chi.Mux, healthRouter *chi.Mux)) *mockSHttp_StartServers_Call {
	_c.Run(run)
	return _c
}

// Started provides a mock function for the type mockSHttp
func (_mock *mockSHttp) Started() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Started")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockSHttp_Started_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Started'
type mockSHttp_Started_Call struct {
	*mock.Call
}

// Started is a helper method to define mock.On call
func (_e *mockSHttp_Expecter) Started() *mockSHttp_Started_Call {
	return &mockSHttp_Started_Call{Call: _e.mock.On("Started")}
}

func (_c *mockSHttp_Started_Call) Run(run func()) *mockSHttp_Started_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockSHttp_Started_Call) Return(b bool) *mockSHttp_Started_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockSHttp_Started_Call) RunAndReturn(run func() bool) *mockSHttp_Started_Call {
	_c.Call.Return(run)
	return _c
}
