// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package idp

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/willie68/arcivio/internal/domain/idp"
)

// newMockIdpProvider creates a new instance of mockIdpProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIdpProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIdpProvider {
	mock := &mockIdpProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockIdpProvider is an autogenerated mock type for the idpProvider type
type mockIdpProvider struct {
	mock.Mock
}

type mockIdpProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIdpProvider) EXPECT() *mockIdpProvider_Expecter {
	return &mockIdpProvider_Expecter{mock: &_m.Mock}
}

// CompleteLogin provides a mock function for the type mockIdpProvider
func (_mock *mockIdpProvider) CompleteLogin(ctx context.Context, requestID string, username string, password string) (idp.LoginResult, error) {
	ret := _mock.Called(ctx, requestID, username, password)

	if len(ret) == 0 {
		panic("no return value specified for CompleteLogin")
	}

	var r0 idp.LoginResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (idp.LoginResult, error)); ok {
		return returnFunc(ctx, requestID, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) idp.LoginResult); ok {
		r0 = returnFunc(ctx, requestID, username, password)
	} else {
		r0 = ret.Get(0).(idp.LoginResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, requestID, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockIdpProvider_CompleteLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteLogin'
type mockIdpProvider_CompleteLogin_Call struct {
	*mock.Call
}

// CompleteLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID string
//   - username string
//   - password string
func (_e *mockIdpProvider_Expecter) CompleteLogin(ctx any, requestID any, username any, password any) *mockIdpProvider_CompleteLogin_Call {
	return &mockIdpProvider_CompleteLogin_Call{Call: _e.mock.On("CompleteLogin", ctx, requestID, username, password)}
}

func (_c *mockIdpProvider_CompleteLogin_Call) Run(run func(ctx context.Context, requestID string, username string, password string)) *mockIdpProvider_CompleteLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockIdpProvider_CompleteLogin_Call) Return(loginResult idp.LoginResult, err error) *mockIdpProvider_CompleteLogin_Call {
	_c.Call.Return(loginResult, err)
	return _c
}

func (_c *mockIdpProvider_CompleteLogin_Call) RunAndReturn(run func(ctx context.Context, requestID string, username string, password string) (idp.LoginResult, error)) *mockIdpProvider_CompleteLogin_Call {
	_c.Call.Return(run)
	return _c
}

// CompletePasswordChange provides a mock function for the type mockIdpProvider
func (_mock *mockIdpProvider) CompletePasswordChange(ctx context.Context, requestID string, oldPassword string, newPassword string) (idp.LoginResult, error) {
	ret := _mock.Called(ctx, requestID, oldPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for CompletePasswordChange")
	}

	var r0 idp.LoginResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (idp.LoginResult, error)); ok {
		return returnFunc(ctx, requestID, oldPassword, newPassword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) idp.LoginResult); ok {
		r0 = returnFunc(ctx, requestID, oldPassword, newPassword)
	} else {
		r0 = ret.Get(0).(idp.LoginResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, requestID, oldPassword, newPassword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockIdpProvider_CompletePasswordChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompletePasswordChange'
type mockIdpProvider_CompletePasswordChange_Call struct {
	*mock.Call
}

// CompletePasswordChange is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID string
//   - oldPassword string
//   - newPassword string
func (_e *mockIdpProvider_Expecter) CompletePasswordChange(ctx any, requestID any, oldPassword any, newPassword any) *mockIdpProvider_CompletePasswordChange_Call {
	return &mockIdpProvider_CompletePasswordChange_Call{Call: _e.mock.On("CompletePasswordChange", ctx, requestID, oldPassword, newPassword)}
}

func (_c *mockIdpProvider_CompletePasswordChange_Call) Run(run func(ctx context.Context, requestID string, oldPassword string, newPassword string)) *mockIdpProvider_CompletePasswordChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockIdpProvider_CompletePasswordChange_Call) Return(loginResult idp.LoginResult, err error) *mockIdpProvider_CompletePasswordChange_Call {
	_c.Call.Return(loginResult, err)
	return _c
}

func (_c *mockIdpProvider_CompletePasswordChange_Call) RunAndReturn(run func(ctx context.Context, requestID string, oldPassword string, newPassword string) (idp.LoginResult, error)) *mockIdpProvider_CompletePasswordChange_Call {
	_c.Call.Return(run)
	return _c
}

// Discovery provides a mock function for the type mockIdpProvider
func (_mock *mockIdpProvider) Discovery() map[string]any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Discovery")
	}

	var r0 map[string]any
	if returnFunc, ok := ret.Get(0).(func() map[string]any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	return r0
}

// mockIdpProvider_Discovery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discovery'
type mockIdpProvider_Discovery_Call struct {
	*mock.Call
}

// Discovery is a helper method to define mock.On call
func (_e *mockIdpProvider_Expecter) Discovery() *mockIdpProvider_Discovery_Call {
	return &mockIdpProvider_Discovery_Call{Call: _e.mock.On("Discovery")}
}

func (_c *mockIdpProvider_Discovery_Call) Run(run func()) *mockIdpProvider_Discovery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockIdpProvider_Discovery_Call) Return(stringToAnyMoqParam map[string]any) *mockIdpProvider_Discovery_Call {
	_c.Call.Return(stringToAnyMoqParam)
	return _c
}

func (_c *mockIdpProvider_Discovery_Call) RunAndReturn(run func() map[string]any) *mockIdpProvider_Discovery_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeToken provides a mock function for the type mockIdpProvider
func (_mock *mockIdpProvider) ExchangeToken(ctx context.Context, req idp.TokenRequest) (*idp.TokenResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeToken")
	}

	var r0 *idp.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, idp.TokenRequest) (*idp.TokenResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, idp.TokenRequest) *idp.TokenResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idp.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, idp.TokenRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockIdpProvider_ExchangeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeToken'
type mockIdpProvider_ExchangeToken_Call struct {
	*mock.Call
}

// ExchangeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req idp.TokenRequest
func (_e *mockIdpProvider_Expecter) ExchangeToken(ctx any, req any) *mockIdpProvider_ExchangeToken_Call {
	return &mockIdpProvider_ExchangeToken_Call{Call: _e.mock.On("ExchangeToken", ctx, req)}
}

func (_c *mockIdpProvider_ExchangeToken_Call) Run(run func(ctx context.Context, req idp.TokenRequest)) *mockIdpProvider_ExchangeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 idp.TokenRequest
		if args[1] != nil {
			arg1 = args[1].(idp.TokenRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockIdpProvider_ExchangeToken_Call) Return(tokenResponse *idp.TokenResponse, err error) *mockIdpProvider_ExchangeToken_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *mockIdpProvider_ExchangeToken_Call) RunAndReturn(run func(ctx context.Context, req idp.TokenRequest) (*idp.TokenResponse, error)) *mockIdpProvider_ExchangeToken_Call {
	_c.Call.Return(run)
	return _c
}

// JWKS provides a mock function for the type mockIdpProvider
func (_mock *mockIdpProvider) JWKS() map[string]any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for JWKS")
	}

	var r0 map[string]any
	if returnFunc, ok := ret.Get(0).(func() map[string]any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	return r0
}

// mockIdpProvider_JWKS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JWKS'
type mockIdpProvider_JWKS_Call struct {
	*mock.Call
}

// JWKS is a helper method to define mock.On call
func (_e *mockIdpProvider_Expecter) JWKS() *mockIdpProvider_JWKS_Call {
	return &mockIdpProvider_JWKS_Call{Call: _e.mock.On("JWKS")}
}

func (_c *mockIdpProvider_JWKS_Call) Run(run func()) *mockIdpProvider_JWKS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockIdpProvider_JWKS_Call) Return(stringToAnyMoqParam map[string]any) *mockIdpProvider_JWKS_Call {
	_c.Call.Return(stringToAnyMoqParam)
	return _c
}

func (_c *mockIdpProvider_JWKS_Call) RunAndReturn(run func() map[string]any) *mockIdpProvider_JWKS_Call {
	_c.Call.Return(run)
	return _c
}

// StartAuthorization provides a mock function for the type mockIdpProvider
func (_mock *mockIdpProvider) StartAuthorization(req idp.AuthorizationRequest) (string, string, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for StartAuthorization")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(idp.AuthorizationRequest) (string, string, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(idp.AuthorizationRequest) string); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(idp.AuthorizationRequest) string); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(idp.AuthorizationRequest) error); ok {
		r2 = returnFunc(req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockIdpProvider_StartAuthorization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAuthorization'
type mockIdpProvider_StartAuthorization_Call struct {
	*mock.Call
}

// StartAuthorization is a helper method to define mock.On call
//   - req idp.AuthorizationRequest
func (_e *mockIdpProvider_Expecter) StartAuthorization(req any) *mockIdpProvider_StartAuthorization_Call {
	return &mockIdpProvider_StartAuthorization_Call{Call: _e.mock.On("StartAuthorization", req)}
}

func (_c *mockIdpProvider_StartAuthorization_Call) Run(run func(req idp.AuthorizationRequest)) *mockIdpProvider_StartAuthorization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 idp.AuthorizationRequest
		if args[0] != nil {
			arg0 = args[0].(idp.AuthorizationRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockIdpProvider_StartAuthorization_Call) Return(s string, s1 string, err error) *mockIdpProvider_StartAuthorization_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *mockIdpProvider_StartAuthorization_Call) RunAndReturn(run func(req idp.AuthorizationRequest) (string, string, error)) *mockIdpProvider_StartAuthorization_Call {
	_c.Call.Return(run)
	return _c
}

// UserInfoFromAccessToken provides a mock function for the type mockIdpProvider
func (_mock *mockIdpProvider) UserInfoFromAccessToken(ctx context.Context, token string) (*idp.UserInfo, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for UserInfoFromAccessToken")
	}

	var r0 *idp.UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*idp.UserInfo, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *idp.UserInfo); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idp.UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockIdpProvider_UserInfoFromAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserInfoFromAccessToken'
type mockIdpProvider_UserInfoFromAccessToken_Call struct {
	*mock.Call
}

// UserInfoFromAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *mockIdpProvider_Expecter) UserInfoFromAccessToken(ctx any, token any) *mockIdpProvider_UserInfoFromAccessToken_Call {
	return &mockIdpProvider_UserInfoFromAccessToken_Call{Call: _e.mock.On("UserInfoFromAccessToken", ctx, token)}
}

func (_c *mockIdpProvider_UserInfoFromAccessToken_Call) Run(run func(ctx context.Context, token string)) *mockIdpProvider_UserInfoFromAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockIdpProvider_UserInfoFromAccessToken_Call) Return(userInfo *idp.UserInfo, err error) *mockIdpProvider_UserInfoFromAccessToken_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *mockIdpProvider_UserInfoFromAccessToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*idp.UserInfo, error)) *mockIdpProvider_UserInfoFromAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
