// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package roles

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/willie68/arcivio/internal/domain/roles"
)

// newMockRolesService creates a new instance of mockRolesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRolesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRolesService {
	mock := &mockRolesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockRolesService is an autogenerated mock type for the rolesService type
type mockRolesService struct {
	mock.Mock
}

type mockRolesService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRolesService) EXPECT() *mockRolesService_Expecter {
	return &mockRolesService_Expecter{mock: &_m.Mock}
}

// GetRole provides a mock function for the type mockRolesService
func (_mock *mockRolesService) GetRole(name string) *roles.RoleDefinition {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 *roles.RoleDefinition
	if returnFunc, ok := ret.Get(0).(func(string) *roles.RoleDefinition); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*roles.RoleDefinition)
		}
	}
	return r0
}

// mockRolesService_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type mockRolesService_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
//   - name string
func (_e *mockRolesService_Expecter) GetRole(name any) *mockRolesService_GetRole_Call {
	return &mockRolesService_GetRole_Call{Call: _e.mock.On("GetRole", name)}
}

func (_c *mockRolesService_GetRole_Call) Run(run func(name string)) *mockRolesService_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockRolesService_GetRole_Call) Return(roleDefinition *roles.RoleDefinition) *mockRolesService_GetRole_Call {
	_c.Call.Return(roleDefinition)
	return _c
}

func (_c *mockRolesService_GetRole_Call) RunAndReturn(run func(name string) *roles.RoleDefinition) *mockRolesService_GetRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoles provides a mock function for the type mockRolesService
func (_mock *mockRolesService) GetRoles() []roles.RoleDefinition {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRoles")
	}

	var r0 []roles.RoleDefinition
	if returnFunc, ok := ret.Get(0).(func() []roles.RoleDefinition); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]roles.RoleDefinition)
		}
	}
	return r0
}

// mockRolesService_GetRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoles'
type mockRolesService_GetRoles_Call struct {
	*mock.Call
}

// GetRoles is a helper method to define mock.On call
func (_e *mockRolesService_Expecter) GetRoles() *mockRolesService_GetRoles_Call {
	return &mockRolesService_GetRoles_Call{Call: _e.mock.On("GetRoles")}
}

func (_c *mockRolesService_GetRoles_Call) Run(run func()) *mockRolesService_GetRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockRolesService_GetRoles_Call) Return(roleDefinitions []roles.RoleDefinition) *mockRolesService_GetRoles_Call {
	_c.Call.Return(roleDefinitions)
	return _c
}

func (_c *mockRolesService_GetRoles_Call) RunAndReturn(run func() []roles.RoleDefinition) *mockRolesService_GetRoles_Call {
	_c.Call.Return(run)
	return _c
}

// HasRole provides a mock function for the type mockRolesService
func (_mock *mockRolesService) HasRole(checkRole string, desiredRole string) bool {
	ret := _mock.Called(checkRole, desiredRole)

	if len(ret) == 0 {
		panic("no return value specified for HasRole")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(checkRole, desiredRole)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockRolesService_HasRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRole'
type mockRolesService_HasRole_Call struct {
	*mock.Call
}

// HasRole is a helper method to define mock.On call
//   - checkRole string
//   - desiredRole string
func (_e *mockRolesService_Expecter) HasRole(checkRole any, desiredRole any) *mockRolesService_HasRole_Call {
	return &mockRolesService_HasRole_Call{Call: _e.mock.On("HasRole", checkRole, desiredRole)}
}

func (_c *mockRolesService_HasRole_Call) Run(run func(checkRole string, desiredRole string)) *mockRolesService_HasRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockRolesService_HasRole_Call) Return(b bool) *mockRolesService_HasRole_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockRolesService_HasRole_Call) RunAndReturn(run func(checkRole string, desiredRole string) bool) *mockRolesService_HasRole_Call {
	_c.Call.Return(run)
	return _c
}
